name: re_anime
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  cached_network_image: ^3.2.3
  intl: ^0.18.1
  spider: ^4.2.1
  dio: ^5.3.2
  carousel_slider: ^4.2.1
  flutter_dotenv: ^5.1.0
  json_annotation: ^4.8.1
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.2
  cupertino_icons: ^1.0.2
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/

  uses-material-design: true
