// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-cNQ9N9VN6m02a3l1EqDBFKyAYfRFo70',
    appId: '1:75887363249:web:ac2c0f64d6d95334850e90',
    messagingSenderId: '75887363249',
    projectId: 'test-reanime',
    authDomain: 'test-reanime.firebaseapp.com',
    storageBucket: 'test-reanime.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmWa0wLQP-0Aj74IBnwXpK8fxotO-gZGs',
    appId: '1:75887363249:android:23316c2f8f3ab526850e90',
    messagingSenderId: '75887363249',
    projectId: 'test-reanime',
    storageBucket: 'test-reanime.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC97HOwAr26ROdbcF2zIuPtU1iLUm5K31M',
    appId: '1:75887363249:ios:f645d9cb36e15f7f850e90',
    messagingSenderId: '75887363249',
    projectId: 'test-reanime',
    storageBucket: 'test-reanime.appspot.com',
    iosBundleId: 'com.example.reAnime',
  );
}
