// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLfdwCvy25yvwt2BTI5_xDwQXolsjH2es',
    appId: '1:215414974777:web:2097daf963d5d4dfce60e8',
    messagingSenderId: '215414974777',
    projectId: 'reanime2-7a26b',
    authDomain: 'reanime2-7a26b.firebaseapp.com',
    storageBucket: 'reanime2-7a26b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY_2MpiLNlgAGKWNVC68zop59mVoBEguU',
    appId: '1:215414974777:android:affb9e0785f0b576ce60e8',
    messagingSenderId: '215414974777',
    projectId: 'reanime2-7a26b',
    storageBucket: 'reanime2-7a26b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANyZrnGPdPlUC3OUG6Usyh9y_4aciqspY',
    appId: '1:215414974777:ios:f7099a6d115c558fce60e8',
    messagingSenderId: '215414974777',
    projectId: 'reanime2-7a26b',
    storageBucket: 'reanime2-7a26b.appspot.com',
    iosBundleId: 'com.example.reAnime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANyZrnGPdPlUC3OUG6Usyh9y_4aciqspY',
    appId: '1:215414974777:ios:83970b97a1421a76ce60e8',
    messagingSenderId: '215414974777',
    projectId: 'reanime2-7a26b',
    storageBucket: 'reanime2-7a26b.appspot.com',
    iosBundleId: 'com.example.reAnime.RunnerTests',
  );
}
