// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqMm_Wlche_aHT6NNhfu2AiqKOMYR0TKM',
    appId: '1:580311443434:web:da019674d28b93d0f87493',
    messagingSenderId: '580311443434',
    projectId: 'reanime-47292',
    authDomain: 'reanime-47292.firebaseapp.com',
    storageBucket: 'reanime-47292.appspot.com',
    measurementId: 'G-HD3Q3G632C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMoLdzcTo7xgLfBKnSJ1b7Mfo5w2axPF0',
    appId: '1:580311443434:android:4b558265cfca52e4f87493',
    messagingSenderId: '580311443434',
    projectId: 'reanime-47292',
    storageBucket: 'reanime-47292.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHwilobMuGnooD6s6Rbz4_sdElUvawtg8',
    appId: '1:580311443434:ios:99f92e93dacbeeebf87493',
    messagingSenderId: '580311443434',
    projectId: 'reanime-47292',
    storageBucket: 'reanime-47292.appspot.com',
    iosBundleId: 'com.example.reAnime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHwilobMuGnooD6s6Rbz4_sdElUvawtg8',
    appId: '1:580311443434:ios:0b5c80d7d47359c4f87493',
    messagingSenderId: '580311443434',
    projectId: 'reanime-47292',
    storageBucket: 'reanime-47292.appspot.com',
    iosBundleId: 'com.example.reAnime.RunnerTests',
  );
}
